[package]
name          = "minicbor-derive"
version       = "0.3.0"
authors       = ["Toralf Wittner <tw@dtex.org>"]
license       = "BlueOak-1.0.0"
edition       = "2018"
description   = "Derive minicbor `Decode` and `Encode` traits."
repository    = "https://gitlab.com/twittner/minicbor"
documentation = "https://twittner.gitlab.io/minicbor/minicbor_derive/"
keywords      = ["cbor", "encoding", "binary"]
categories    = ["encoding"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.9"
quote       = "1.0.2"
syn         = "1.0.16"

[dev-dependencies]
minicbor = { path = "../minicbor", features = ["std", "derive"] }
